In [3]:
import math
x,y=-3,4

In [4]:
# forward pass
sigy = 1.0 / (1 + math.exp(-y)) # sigmoid in numerator   #(1)
num = x + sigy # numerator                               #(2)
sigx = 1.0 / (1 + math.exp(-x)) # sigmoid in denominator #(3)
xpy = x + y                                              #(4)
xpysqr = xpy**2                                          #(5)
den = sigx + xpysqr # denominator                        #(6)
invden = 1.0 / den                                       #(7)
f = num * invden # done!  

In [5]:
print "sigy:",sigy

sigy: 0.982013790038


In [6]:
num

-2.0179862099620918

In [7]:
sigx

0.04742587317756678

In [9]:
xpy

1

In [10]:
xpysqr

1

In [11]:
den

1.0474258731775667

In [12]:
invden

0.954721499256371

In [13]:
f

-1.92661481985369

In [14]:
# backprop f = num * invden
dnum = invden # gradient on numerator                             #(8)
dinvden = num 

In [15]:
dnum

0.954721499256371

In [16]:
dinvden

-2.0179862099620918

In [17]:
dden = (-1.0 / (den**2)) * dinvden 

In [18]:
dden

1.839380589300258

In [19]:
dsigx = (1) * dden                                                #(6)
dxpysqr = (1) * dden  

In [20]:
dsigx

1.839380589300258

In [21]:
dxpy = (2 * xpy) * dxpysqr

In [22]:
dxpy

3.678761178600516

In [23]:
dx = (1) * dxpy                                                   #(4)
dy = (1) * dxpy                                                   #(4)
# backprop sigx = 1.0 / (1 + math.exp(-x))
dx += ((1 - sigx) * sigx) * dsigx # Notice += !! See notes below  #(3)
# backprop num = x + sigy
dx += (1) * dnum                                                  #(2)
dsigy = (1) * dnum                                                #(2)
# backprop sigy = 1.0 / (1 + math.exp(-y))
dy += ((1 - sigy) * sigy) * dsigy

In [24]:
dx

4.716579748855349

In [25]:
dy

3.695624143957394

The forward expression involves the variables x,y multiple times, so when we perform backpropagation we must be careful to use += instead of = to accumulate the gradient on these variables (otherwise we would overwrite it). This follows the multivariable chain rule in Calculus, which states that if a variable branches out to different parts of the circuit, then the gradients that flow back to it will add.

In [45]:
x,y,z=1,2,2

In [46]:
u=x*y

In [47]:
v=y*z

In [48]:
u

2

In [49]:
v

4

In [50]:
s=u*v

In [51]:
s

8

In [52]:
dus=v

In [53]:
dvs=u

In [54]:
dus

4

In [55]:
dvs

2

In [56]:
dxs=dus*y

In [57]:
dxs

8

In [58]:
dys=dus*x

In [59]:
dys

4

In [60]:
dys+=dvs*z

In [61]:
dys

8

In [63]:
import numpy as np
X1=np.array([1,2])

In [64]:
W1=np.arange(4)

In [65]:
W1

array([0, 1, 2, 3])

In [66]:
W1.reshape((2,2))

array([[0, 1],
       [2, 3]])

In [67]:
W1

array([0, 1, 2, 3])

In [68]:
W1=W1.reshape((2,2))

In [69]:
W1

array([[0, 1],
       [2, 3]])

In [70]:
H=X1.dot(W1)

In [71]:
H

array([4, 7])

In [72]:
W2=np.array([1,3,4,2])

In [73]:
W2=W2.reshape((2,2))

In [74]:
W2

array([[1, 3],
       [4, 2]])

In [75]:
S=H.dot(W2)

In [76]:
S

array([32, 26])