In [1]:
import numpy as np

In [2]:
D=np.random.randn(1000,500)

In [3]:
D

array([[ 1.44300983, -1.21422013,  1.01129372, ..., -1.53462859,
        -1.03387747,  0.0134063 ],
       [ 1.07790838, -0.15192507,  0.09881205, ..., -1.08644665,
         1.97363225, -0.91656912],
       [ 0.65571081,  0.1327674 , -1.81800796, ...,  1.00565554,
        -1.07409884, -1.02664959],
       ..., 
       [ 0.36447842, -0.74841865,  0.64756377, ...,  1.35348978,
         0.23823365, -0.7572482 ],
       [-0.81653707, -0.40789582,  0.16736221, ..., -0.38950829,
        -1.39546656, -0.24540926],
       [ 0.5912545 ,  0.58027404,  2.07976302, ..., -0.91842095,
        -1.47171773, -0.79486486]])

In [4]:
D.max

<function max>

In [5]:
D.max()

4.657757577332359

In [6]:
D.min()

-4.5897333956362525

In [7]:
D.mean()

-0.00047554265507178048

In [8]:
D.std()

1.000547111798693

D is a Gaussian distribution

In [9]:
Hidden_layer_sizes=[500]*10

In [10]:
Hidden_layer_sizes

[500, 500, 500, 500, 500, 500, 500, 500, 500, 500]

In [11]:
a=[500]

In [12]:
a

[500]

In [13]:
b=np.array([500])

In [14]:
b

array([500])

In [15]:
b*10

array([5000])

In [16]:
nonlinears=['tanh']*len(Hidden_layer_sizes)

In [17]:
nonlinears

['tanh',
 'tanh',
 'tanh',
 'tanh',
 'tanh',
 'tanh',
 'tanh',
 'tanh',
 'tanh',
 'tanh']

In [18]:
act={'relu':lambda x:np.maximun(0,x), 'tanh':lambda x:np.tanh(x)}

In [19]:
act

{'relu': <function __main__.<lambda>>, 'tanh': <function __main__.<lambda>>}

In [20]:
Hs={}

In [24]:
for i in xrange(len(Hidden_layer_sizes)):
    X=D if i==0 else Hs[i-1]
    fan_in=X.shape[1]
    fan_out=Hidden_layer_sizes[i]
    W=np.random.randn(fan_in,fan_out)*0.01
    H=np.dot(X,W)
    H=act[nonlinears[i]](H)
    #print(act[nonlinears[i]](H))
    Hs[i]=H
    #print X[:10]

[[ 1.44300983 -1.21422013  1.01129372 ..., -1.53462859 -1.03387747
   0.0134063 ]
 [ 1.07790838 -0.15192507  0.09881205 ..., -1.08644665  1.97363225
  -0.91656912]
 [ 0.65571081  0.1327674  -1.81800796 ...,  1.00565554 -1.07409884
  -1.02664959]
 ..., 
 [-0.60245563 -0.32533489  1.60886628 ..., -1.62149441  0.24434811
  -1.17762657]
 [ 0.82664435 -0.49654862  1.22719256 ...,  1.07941282  0.49717403
  -0.9545686 ]
 [-0.61345019  1.03707317 -0.94192196 ..., -0.28365206 -0.61032493
   1.07975328]]
[[-0.31859319  0.32709366 -0.29356363 ..., -0.23995563 -0.31142697
   0.19169483]
 [-0.21333415  0.11789223 -0.32999096 ...,  0.00152845  0.26610561
   0.28833812]
 [ 0.17226857 -0.01880954 -0.00152657 ..., -0.03315102 -0.19914369
  -0.3591377 ]
 ..., 
 [ 0.09505608  0.168307   -0.15209156 ..., -0.08937166  0.25356005
   0.03325585]
 [-0.11857115 -0.10767735  0.01559903 ...,  0.07686122  0.04660289
   0.20126662]
 [-0.00408463 -0.23400016 -0.01701344 ...,  0.05068479  0.02424177
  -0.47764066]]
