Implement Jacobian matrix for softmax array

In [1]:
import numpy as np

In [2]:
X=np.array([1,2,3])

In [3]:
X.shape[0]

3

In [4]:
def softmax(x):
    """Compute the softmax of vector x."""
    exps = np.exp(x)
    return exps / np.sum(exps)

In [5]:
S=softmax(X)

In [6]:
S

array([ 0.09003057,  0.24472847,  0.66524096])

In [7]:
D=np.zeros((X.shape[0],S.shape[0]))

In [8]:
D

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [9]:
def cal_derivation(X,S,D):
    for i in range(X.shape[0]):
        for j in range(S.shape[0]):
            if i==j:
                D[i,j]=S[i]*(1-S[j])
            else:
                D[i,j]=-S[i]*S[j]
    return D

In [10]:
D=cal_derivation(X,S,D)
D

array([[ 0.08192507, -0.02203304, -0.05989202],
       [-0.02203304,  0.18483645, -0.1628034 ],
       [-0.05989202, -0.1628034 ,  0.22269543]])

In [11]:
X1=np.arange(9)

In [12]:
X1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
W=np.ones((3,9))

In [14]:
W

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [15]:
b=np.array([0,2,1])

In [16]:
b

array([0, 2, 1])

In [17]:
b.reshape(1,-1)

array([[0, 2, 1]])

In [18]:
Y=W.dot(X1)+b

In [19]:
Y

array([ 36.,  38.,  37.])

In [20]:
S=softmax(Y)

In [21]:
S
D=np.zeros((Y.shape[0],S.shape[0]))

In [22]:
DyS=cal_derivation(Y,S,D)

In [23]:
DyS

array([[ 0.08192507, -0.05989202, -0.02203304],
       [-0.05989202,  0.22269543, -0.1628034 ],
       [-0.02203304, -0.1628034 ,  0.18483645]])

In [24]:
DwY=np.zeros((Y.shape[0], W.shape[0]*W.shape[1]))

In [25]:
DwY.shape

(3, 27)

In [26]:
count=0
for t in range(Y.shape[0]):
    #print t
    for i in range(Y.shape[0]):
        for j in range(W.shape[1]):
            if(i==t):
                DwY[t,(i)*W.shape[0]+j]=X1[j]
               

In [27]:
X1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
DwY

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,
         7.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.]])

In [30]:
# forward pass
W = np.random.randn(5, 10)
X = np.random.randn(10, 3)
D = W.dot(X)




In [31]:
W.shape

(5, 10)

In [32]:
X.shape

(10, 3)

In [38]:
D.shape

(5, 3)

In [39]:
# now suppose we had the gradient on D from above in the circuit
dD = np.random.randn(*D.shape) # same shape as D
dW = dD.dot(X.T) #.T gives the transpose of the matrix
dX = W.T.dot(dD)

In [35]:
dD.shape

(5, 3)

In [40]:
D.shape

SyntaxError: invalid syntax (<ipython-input-40-f2127912a927>, line 1)