In [1]:
import numpy as np

In [2]:
X=np.arange(9)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
X=X.reshape((3,3))

In [5]:
y=np.argmin(X,axis=1)
y

array([0, 0, 0])

In [6]:
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
X[0]

array([0, 1, 2])

In [6]:
W=np.arange(6)

In [7]:
W

array([0, 1, 2, 3, 4, 5])

In [8]:
W=W.reshape((3,2))
W

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
for i in range(X.shape[0]):
    print X[i].dot(W)

[10 13]
[28 40]
[46 67]


In [10]:
dW = np.zeros(W.shape)

In [12]:
dW

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [13]:
dW[:,1]+=X[1,]

In [14]:
X[1,]

array([3, 4, 5])

In [15]:
dW

array([[ 0.,  3.],
       [ 0.,  4.],
       [ 0.,  5.]])